### ISSUE TITLE
Roadmap to 1.5

### ISSUE THREAD

**Issue by 0xWDG** [wdg/CodeEditor#5]
Version 1.5
- [x] enable console (inline console window)
- [x] build (build directly from the editor)
- [x] show images in image viewer

Version 2.0:
- [x] show pdf in pdf viewer
- [ ] on error. (show errors and allow user to jump to file and line)
- [ ] research quick view functionality

**Comment by gaetandezeiraud** [comment]
Hi! 
I propose a markdown viewer for 1.5. I can make it. 
 _build (build directly from the editor)_ only for Swift? I think, it can be a good idea to add makefile support for C & C++. And, why not, run `npm start` for NodeJS if package.json exist.

For version 2.0, maybe the possibility to open multiple tab (files)?

**Comment by 0xWDG** [comment]
Sounds great!

**Comment by gaetandezeiraud** [comment]
WIP for build button. See 842782a443a1d32a613393b898ec52b2f682b8c9
Makefile build work without problem. But, I can not run npm, it return `env: npm: No such file or directory` but npm is in my environment (installation with Brew).

**Comment by 0xWDG** [comment]
`npm` does now work better.
it does not work yet, but it at least loads node.js (and npm).

    [17/5/2019 19:35.48] /usr/local/bin/npm: line 2: syntax error near unexpected token `;'
    /usr/local/bin/npm: line 2: `;(function () { // wrapper in case we're in module_context mode'

If you press build you can see the output in the "console" view, it will open if you press build 😁

**Comment by 0xWDG** [comment]
Build a c file
<img width="1112" alt="Screenshot 2019-05-17 at 19 39 53" src="https://user-images.githubusercontent.com/1290461/57946029-9d13c400-78db-11e9-844e-4095d6f2873b.png">

build npm
<img width="1112" alt="Screenshot 2019-05-17 at 19 39 29" src="https://user-images.githubusercontent.com/1290461/57946031-9d13c400-78db-11e9-8bc7-859026dd56c8.png">

(the console does not resize automatically, on the first screenshot I resized it, the second screenshot shows the original size of the console (which is a little to small in my opinion).

**Comment by gaetandezeiraud** [comment]
Hi!
Sorry, very busy lately. I'm agree, the first screenshot is better!
I have made a pull request for **show images in image viewer**. I open it with Quickview. So, it's working also for pdf and more. This seems me to be good idea.

**Comment by 0xWDG** [comment]
Hi @Brouilles,

i was thinking of re-starting this project again,
it you have any ideas, or still want to help that would be great!

**Comment by gaetandezeiraud** [comment]
Hi! 
I hope you are well!
Good luck with the project. I have abandoned the Apple ecosystem since the last time. So I no longer have a computer with mac os.

Have a good day!
